"""Deterministic SYSTEM FAQ routing and retrieval.

The module has no FastAPI, LangChain, or model-provider dependency so the
SYSTEM domain can be tested without building the seven-office FAISS index.  FAQ
answers are extractive-first: a matched answer is returned verbatim from the
shared structured content file instead of being regenerated by an LLM.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Any


DEFAULT_CONTENT_PATH = Path(__file__).resolve().parent / "system_content.json"


class QueryDomain(str, Enum):
    SYSTEM = "SYSTEM"
    OPE = "OPE"
    GE = "GE"
    LC = "LC"
    OAA = "OAA"
    OSA = "OSA"
    HR = "HR"
    OGA = "OGA"
    OTHER = "OTHER"


@dataclass(frozen=True)
class SystemFAQMatch:
    faq_id: str
    score: float
    exact: bool
    faq: dict[str, Any]

    def answer(self, language: str = "zh-TW") -> str:
        return str(self.faq["answer_en" if language.lower().startswith("en") else "answer_zh"])

    def source(self, language: str = "zh-TW") -> dict[str, str]:
        raw = self.faq["source"]
        return {
            "type": "system",
            "title": str(raw["title_en" if language.lower().startswith("en") else "title_zh"]),
            "url": str(raw["url"]),
            "faq_id": self.faq_id,
        }


_SYSTEM_CUES = (
    "這個系統", "本系統", "這網站", "這個網站", "aia.ntpu.ai", "智慧問答",
    "你可以", "你能", "你會", "你有", "你知道", "你了解", "你的資料", "你的回答", "你是",
    "服務範圍", "支援哪些", "支援什麼", "怎麼使用", "怎麼用", "登入",
    "註冊", "資料來源", "知識庫", "更新一次", "更新頻率", "對話內容",
    "隱私", "追問", "上一題", "chatgpt", "回答不了", "回報錯誤",
    "this system", "this site", "aia.ntpu.ai", "what can you", "can you",
    "do you", "your data", "your source", "how do i use", "how often", "updated",
    "can i ask", "in english", "sign in", "login",
    "register", "privacy", "follow-up", "follow up", "chatgpt", "knowledge base",
    "supported offices", "system support", "report an error",
)

_CAPABILITY_CUES = (
    "你有", "你知道", "你了解", "可以回答", "能回答", "可以查", "能查", "支援", "服務範圍",
    "有哪些功能", "有沒有資料", "what can", "can you answer", "do you have",
    "does this system support", "what does this system support", "which offices",
)

_OFFICE_CONTENT_CUES = (
    "體育", "運動", "場地", "通識", "向度", "語言中心", "英文免修", "多益",
    "toeic", "托福", "toefl", "雅思", "ielts", "教務", "學籍", "休學", "復學",
    "選課", "學分", "成績", "畢業", "學務", "宿舍", "住宿", "助學金", "社團",
    "人事", "差勤", "刷卡", "病假", "事假", "請假", "體育館",
    "總務", "報修", "營繕", "採購", "財產", "出納", "停車證", "電子公文",
    "sports center", "physical education", "general education", "language center",
    "toeic", "toefl", "ielts", "credit", "leave of absence", "course selection",
    "academic affairs", "student affairs", "dorm", "scholarship", "personnel",
    "attendance", "sick leave", "general affairs", "procurement", "parking permit",
)

_PERSONAL_RECORD_REQUEST_RE = re.compile(
    r"(?:你|本系統|這個系統|系統|網站).{0,8}(?:可以|能|會).{0,8}"
    r"(?:幫我|替我|為我)?(?:查|看|讀取|存取|取得).{0,8}"
    r"(?:我的|本人的|個人).{0,8}(?:成績|學籍|帳務|繳費|帳戶|資料)"
    r"|(?:幫我|替我|為我)(?:查|看|讀取|存取|取得).{0,8}"
    r"(?:我的|本人的|個人).{0,8}(?:成績|學籍|帳務|繳費|帳戶|資料)"
    r"|\bcan\s+(?:you|this\s+(?:system|site))\b.{0,24}"
    r"\b(?:my\s+)?(?:grades?|student\s+record|account|billing)\b",
    re.IGNORECASE,
)


def _normalize(text: str) -> str:
    text = str(text or "").strip().lower()
    return re.sub(r"[^a-z0-9\u4e00-\u9fff]+", "", text)


def _features(text: str) -> set[str]:
    lowered = str(text or "").lower()
    result = set(re.findall(r"[a-z0-9]+", lowered))
    for segment in re.findall(r"[\u4e00-\u9fff]+", lowered):
        if len(segment) == 1:
            result.add(segment)
        else:
            result.update(segment[i:i + 2] for i in range(len(segment) - 1))
    return result


def detect_language(query: str) -> str:
    """Return the response language expected by the SYSTEM FAQ."""
    return "zh-TW" if re.search(r"[\u4e00-\u9fff]", query or "") else "en"


def _has_any(text: str, phrases: tuple[str, ...]) -> bool:
    lowered = str(text or "").lower()
    return any(phrase in lowered for phrase in phrases)


def _is_personal_record_request(query: str) -> bool:
    """Return whether the user asks this public FAQ bot to access private records."""
    return bool(_PERSONAL_RECORD_REQUEST_RE.search(str(query or "")))


class SystemFAQRetriever:
    def __init__(self, content_path: str | Path = DEFAULT_CONTENT_PATH):
        self.content_path = Path(content_path)
        with self.content_path.open("r", encoding="utf-8") as handle:
            content = json.load(handle)
        faqs = content.get("faqs") if isinstance(content, dict) else None
        if not isinstance(faqs, list) or len(faqs) < 15:
            raise ValueError("SYSTEM FAQ content must contain at least 15 entries")
        self.content = content
        self.faqs = faqs

    @staticmethod
    def _score(query: str, faq: dict[str, Any]) -> tuple[float, bool]:
        q_norm = _normalize(query)
        q_features = _features(query)
        phrases = [
            faq.get("question_zh", ""),
            faq.get("question_en", ""),
            *(faq.get("aliases_zh") or []),
            *(faq.get("aliases_en") or []),
        ]
        best = 0.0
        exact = False
        for phrase in phrases:
            p_norm = _normalize(phrase)
            if not p_norm:
                continue
            if q_norm == p_norm:
                return 1.0, True
            if min(len(q_norm), len(p_norm)) >= 4 and (q_norm in p_norm or p_norm in q_norm):
                containment = min(len(q_norm), len(p_norm)) / max(len(q_norm), len(p_norm))
                best = max(best, 0.82 + 0.14 * containment)
            p_features = _features(phrase)
            overlap = len(q_features & p_features)
            if overlap:
                coverage = overlap / max(1, len(q_features))
                candidate_coverage = overlap / max(1, len(p_features))
                jaccard = overlap / max(1, len(q_features | p_features))
                best = max(best, 0.48 * coverage + 0.34 * candidate_coverage + 0.18 * jaccard)

        keyword_features = _features(" ".join(str(x) for x in faq.get("keywords", [])))
        keyword_overlap = len(q_features & keyword_features)
        if keyword_overlap:
            keyword_coverage = keyword_overlap / max(1, len(q_features))
            best = max(best, 0.58 * keyword_coverage + 0.18)
        # Capability questions often contain a variable office/topic name
        # (for example, "你有語言中心免修的資料嗎").  Route the intent to the
        # capability FAQ without teaching the lexical retriever every topic.
        if faq.get("id") == "system-capabilities" and _has_any(query, _CAPABILITY_CUES):
            best = max(best, 0.76)
        if faq.get("id") == "system-privacy" and _is_personal_record_request(query):
            best = max(best, 0.92)
        return min(1.0, best), exact

    def search(self, query: str, top_k: int = 3) -> list[SystemFAQMatch]:
        matches = []
        for faq in self.faqs:
            score, exact = self._score(query, faq)
            matches.append(SystemFAQMatch(str(faq["id"]), score, exact, faq))
        matches.sort(key=lambda item: item.score, reverse=True)
        return matches[:max(1, int(top_k))]

    def best(self, query: str) -> SystemFAQMatch:
        return self.search(query, top_k=1)[0]


def should_route_system(
    query: str,
    match: SystemFAQMatch,
    *,
    threshold: float,
) -> bool:
    """Conservatively classify explicit questions about the assistant itself."""
    if match.score < threshold:
        return False
    personal_record_request = _is_personal_record_request(query)
    has_system_cue = _has_any(query, _SYSTEM_CUES)
    if match.exact and (has_system_cue or _has_any(query, _CAPABILITY_CUES) or personal_record_request):
        return True
    if not has_system_cue and not personal_record_request:
        return False

    # Office-detail questions must keep using the seven-office RAG unless the user
    # is explicitly asking whether the system has/supports that information.
    if (
        _has_any(query, _OFFICE_CONTENT_CUES)
        and not _has_any(query, _CAPABILITY_CUES)
        and not personal_record_request
    ):
        return False
    return True


def should_use_system_fallback(
    query: str,
    match: SystemFAQMatch,
    *,
    threshold: float,
) -> bool:
    """Apply a stricter SYSTEM match after the ordinary router says OTHER."""
    if match.score < threshold:
        return False
    if match.exact:
        return True
    personal_record_request = _is_personal_record_request(query)
    if (
        _has_any(query, _OFFICE_CONTENT_CUES)
        and not _has_any(query, _CAPABILITY_CUES)
        and not personal_record_request
    ):
        return False
    return personal_record_request or _has_any(query, _SYSTEM_CUES)
